### ISSUE TITLE
Bump to pipeline 0.27 and triggers 0.16

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/cli#1431]
This includes the following tasks

 - [x] Bump to pipeline 0.27.0
 - [x] Bump to triggers 0.16
 - [x] Support for v1beta1 triggers resources
 - [x] Move e2e to triggers v1beta1

**Comment by piyush-garg** [comment]
Pipeline Bump PR https://github.com/tektoncd/cli/pull/1438/

**Comment by piyush-garg** [comment]
Trigger bump and trigger template v1beta1 work #1446

**Comment by vinamra28** [comment]
Should we bump pipelines to 0.28 as well?

**Comment by pradeepitm12** [comment]
>Should we bump pipelines to 0.28 as well?

How about doing that in a separate pr. It would make it easier to review

**Comment by piyush-garg** [comment]
PR #1449 for triggerbinding and #1450 for clustertriggerbinding

**Comment by piyush-garg** [comment]
> Should we bump pipelines to 0.28 as well?

@vinamra28 It has been done as part of #1448

**Comment by piyush-garg** [comment]
PRs #1454 and #1455 for eventlistener

**Comment by piyush-garg** [comment]
E2E test PR https://github.com/tektoncd/cli/pull/1458

**Comment by piyush-garg** [comment]
All stories done 
/close
