### ISSUE TITLE
Inputs/Outputs/Params No Longer Being Displayed in Describe Commands

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#817]
I am assuming the switch to the spec in pipeline where inputs/outputs/params are under resources/spec has broken describe commands, which still reference these values using the old structure:

https://github.com/tektoncd/cli/blob/95ed643507bcda2235ba9c598871beb2fa04607d/pkg/cmd/task/describe.go#L52

Perhaps an update to `spec.resources.inputs`, `spec.resources.outputs`, and `spec.params` is the fix.

**Version:** 

```
tkn version
Client version: 0.8.0
Pipeline version: v0.11.0-rc2
```

# Expected Behavior

Input/Output/Params are displayed when describing resources.

# Actual Behavior

```
$ tkn t desc build-docker-image-from-git-source

tkn t desc build-docker-image-from-git-source
Name:        build-docker-image-from-git-source
Namespace:   default

📨 Input Resources

 No input resources

📡 Output Resources

 No output resources

⚓ Params

 No params

🦶 Steps

 ∙ build-and-push

🗂  Taskruns

NAME                                           STARTED          DURATION    STATUS
build-docker-image-from-git-source-run-bzgl6   50 minutes ago   4 minutes   Succeeded
```

# Additional Info

YAML for Task:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: /workspace/docker-source/Dockerfile
    - name: pathToContext
      type: string
      description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: /workspace/docker-source
  resources:
    inputs:
      - name: docker-source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.17.1
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToDockerFile)
        - --destination=$(resources.outputs.builtImage.url)
        - --context=$(params.pathToContext)
```

**Comment by piyush-garg** [comment]
I think this is also related to task and clustertask

**Comment by danielhelfand** [comment]
> I think this is also related to task and clustertask

It's for all resources I am pretty sure.

**Comment by christopherfrieler** [comment]
I just experienced this bug, too. It seems, starting tasks is also affected:

`tkn task start -p myparam=value` fails with the message that myparam was not part of the spec, although it definitely is. I could still start the Task with the parameter by writing a TaskRun.yaml-file and applying it through `kubectl apply -f TaskRun.yaml`. But that's not a complete workaround, because this way I would have to generate unique identifiers for the TaskRuns myself.

**Comment by danielhelfand** [comment]
@christopherfrieler Thanks for the additional information on `tkn task start`. Would you mind sharing the version of pipelines you are using? Posting the output of `tkn version` would be really helpful as we work towards supporting the `v1beta1` API.

**Comment by piyush-garg** [comment]
I think this issue is related to some resources only

- [ ] Task - Raised PR #870 
- [ ] ClusterTask - Raised PR #888 
- [ ] Taskrun - Raised PR #884 

Let me know if you face this with Pipeline or PipelineRun

**Comment by danielhelfand** [comment]
Yeah, I believe you're correct. It seems what this came down to was the changes in Task in a Task Spec. Possibly to more closely align it with how Pipeline's spec is.

**Comment by piyush-garg** [comment]
All three PR's are merged. I am closing this issue now.
